<p class="terug">
    <a href="/producten">&lt; Terug naar overzicht</a>
</p>

<article class="detail">
    <h2 class="big">Product 1</h2>
    <img src="http://placehold.it/405x300" alt="product 1">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dolor tellus, gravida ac molestie eu, iaculis nec sem. Etiam quis dui vitae elit varius tincidunt. Praesent et purus magna, eu tincidunt dui. Aliquam in nisl elit, id aliquam magna. Quisque venenatis viverra hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultricies erat dui, eu tempor dolor.
    </p>
    <p class="prijs">
        &euro; 999
    </p>
    <p class="bestel">
        <a href="#">
            Toevoegen aan winkelmandje (+)
        </a>
    </p>
</article>

<p class="terug">
    <a href="/producten">&lt; Terug naar overzicht</a>
</p>